platform:ios, "9.0"


target 'NiriAI' do
  pod 'ApiAI/Core' #, :path => '../'
  pod 'ApiAI/VoiceRequest' #, :path => '../'
  pod 'ApiAI/UIKit' #, :path => '../'
  pod 'ApiAI/ResponseMapping' #, :path => '../'
  pod 'MBProgressHUD'
end
